[scrolling]
history = 100000

[window]
padding = { x = 5, y = 5 }
option_as_alt = "OnlyLeft"
opacity = 0.90
blur = true

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 13

[cursor]
style = { shape = "Block" }
vi_mode_style = { shape = "Beam" }
